development: &development
  adapter: postgresql
  encoding: utf8
  host: "<%= ENV['DATABASE_HOST'] || 'localhost' %>"
  port: 5432
  database: book_storm_new_development
  username: postgres
  password: 24373514
  pool: 5

test:
  <<: *development
  database: book_storm_new_test

production:
  <<: *development
  database: book_storm_new_production
  username: book_storm_new
  password: book_storm_new_db_admin
  pool: 25